language: elixir
elixir:
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
otp_release:
 - 19.3
 - 20.3
 - 21.2
matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.2
    - elixir: 1.5
      otp_release: 21.2
